import { create } from 'zustand';

export const AVAILABLE_MODELS = [
    { id: 'gpt-4o', name: 'ChatGPT GPT-4o', provider: 'OpenAI', icon: '🤖', badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' },
    { id: 'claude-3-5-sonnet', name: 'Claude 3.5 Sonnet', provider: 'Anthropic', icon: '🧠', badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20' },
    { id: 'gemini-1-5-pro', name: 'Gemini 1.5 Pro', provider: 'Google', icon: '♊', badgeColor: 'bg-blue-500/10 text-blue-400 border-blue-500/20' },
    { id: 'grok-2', name: 'Grok-2', provider: 'xAI', icon: '⚡', badgeColor: 'bg-purple-500/10 text-purple-400 border-purple-500/20' },
    { id: 'deepseek-r1', name: 'DeepSeek R1', provider: 'DeepSeek', icon: '🔬', badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20' }
];

export const PROJECT_TYPES = [
    { id: 'web-app', label: 'Web App', desc: 'Full-stack MERN/React app + Database', icon: '💻' },
    { id: 'website', label: 'Website', desc: 'High-converting marketing site', icon: '🌐' },
    { id: 'workflow', label: 'Workflow', desc: 'Trigger-action automation flow', icon: '⚡' },
    { id: 'design', label: 'Design Mode', desc: 'UI/UX wireframes & prototypes', icon: '🎨' }
];

const INITIAL_FILE_TREE = {
    'src/App.jsx': `import React, { useState } from 'react';\nimport { Shield, Sparkles, Activity, CreditCard, Users } from 'lucide-react';\n\nexport default function App() {\n  const [metrics] = useState({\n    users: '12,480',\n    revenue: '$48,290',\n    uptime: '99.99%',\n    activeNodes: 64\n  });\n\n  return (\n    <div className="min-h-screen bg-slate-950 text-white p-8 font-sans">\n      <header className="flex justify-between items-center pb-6 border-b border-slate-900">\n        <div className="flex items-center gap-3">\n          <div className="w-10 h-10 rounded-xl bg-indigo-600 flex items-center justify-center font-bold text-white shadow-lg shadow-indigo-500/30">\n            AI\n          </div>\n          <div>\n            <h1 className="text-xl font-extrabold tracking-tight">DeepIT AI Generated SaaS</h1>\n            <p className="text-xs text-slate-400">Deployed via DeepitLabs Build Studio</p>\n          </div>\n        </div>\n        <button className="bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold px-4 py-2 rounded-lg transition-all shadow-md">\n          Launch Production\n        </button>\n      </header>\n\n      <main className="mt-8 space-y-6">\n        <div className="grid grid-cols-1 md:grid-cols-4 gap-5">\n          <Card title="Total Subscribers" value={metrics.users} icon={Users} color="indigo" />\n          <Card title="Monthly Revenue" value={metrics.revenue} icon={CreditCard} color="emerald" />\n          <Card title="System Health" value={metrics.uptime} icon={Shield} color="violet" />\n          <Card title="Compute Cluster" value={metrics.activeNodes} icon={Activity} color="amber" />\n        </div>\n\n        <div className="p-6 bg-slate-900/40 border border-slate-800/80 rounded-2xl backdrop-blur-md">\n          <h3 className="text-sm font-bold text-white flex items-center gap-2 mb-2">\n            <Sparkles className="w-4 h-4 text-indigo-400" /> Live Interactive Application Sandbox\n          </h3>\n          <p className="text-xs text-slate-400">\n            This application was generated by the AI Build Agent. Edit code in the Code Editor tab to update this live view instantly.\n          </p>\n        </div>\n      </main>\n    </div>\n  );\n}\n\nfunction Card({ title, value, icon: Icon, color }) {\n  return (\n    <div className="p-5 bg-slate-900/60 border border-slate-800 rounded-2xl flex justify-between items-start">\n      <div>\n        <span className="text-[10px] uppercase font-semibold text-slate-400 tracking-wider">{title}</span>\n        <h2 className="text-2xl font-black text-white mt-1">{value}</h2>\n      </div>\n      <div className={\`p-2.5 rounded-xl bg-\${color}-500/10 text-\${color}-400\`}>\n        <Icon className="w-5 h-5" />\n      </div>\n    </div>\n  );\n}`,
    'src/index.css': `@import "tailwindcss";\n\nbody {\n  background-color: #020617;\n  color: #f8fafc;\n  font-family: ui-sans-serif, system-ui, sans-serif;\n}`,
    'server.js': `const express = require('express');\nconst app = express();\nconst PORT = process.env.PORT || 5000;\n\napp.use(express.json());\n\napp.get('/api/health', (req, res) => {\n  res.json({ status: 'online', timestamp: new Date() });\n});\n\napp.listen(PORT, () => {\n  console.log(\`Server running on port \${PORT}\`);\n});`
};

export const useBuilderStore = create((set, get) => ({
    selectedModel: 'gpt-4o',
    projectType: 'web-app',
    projectTitle: 'DeepIT AI Generated SaaS',
    isSaved: true,
    isBuilding: false,
    
    // Multi-tab Workspace state
    viewMode: 'preview', // 'preview' | 'code' | 'console'
    viewport: 'desktop', // 'desktop' | 'tablet' | 'mobile'
    
    // File tree state
    fileTree: INITIAL_FILE_TREE,
    activeFilePath: 'src/App.jsx',

    // Console logs state
    buildLogs: [
        '[System] DeepitLabs Sandbox Environment Initialized',
        '[System] Virtual container mounted on port 5173',
        '[Agent] Ready for natural language prompt requests'
    ],

    // Deploy Modal state
    isDeployModalOpen: false,
    deployUrl: null,
    isDeploying: false,
    deployLogs: [],

    // Chat History
    messages: [
        {
            id: 'msg-init',
            role: 'assistant',
            model: 'gpt-4o',
            content: 'Hello! I am your DeepitLabs AI Agent. Describe what you would like to build (Web App, Website, Automation Workflow, or UI Design), select your AI model, and I will generate the complete codebase, backend schemas, and live interactive preview for you.',
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        }
    ],

    // Actions
    setSelectedModel: (model) => set({ selectedModel: model }),
    setProjectType: (type) => set({ projectType: type }),
    setProjectTitle: (title) => set({ projectTitle: title, isSaved: false }),
    setViewMode: (mode) => set({ viewMode: mode }),
    setViewport: (vp) => set({ viewport: vp }),
    setActiveFilePath: (path) => set({ activeFilePath: path }),

    updateFileContent: (path, newContent) => set((state) => ({
        fileTree: { ...state.fileTree, [path]: newContent },
        isSaved: false
    })),

    saveProject: () => {
        set({ isSaved: true });
    },

    setDeployModalOpen: (isOpen) => set({ isDeployModalOpen: isOpen }),

    // Prompt Submission & Simulated AI Agent Execution Pipeline
    sendMessage: async (promptText) => {
        if (!promptText.trim()) return;

        const state = get();
        const userMsg = {
            id: `user-${Date.now()}`,
            role: 'user',
            content: promptText,
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        };

        const activeModel = AVAILABLE_MODELS.find(m => m.id === state.selectedModel) || AVAILABLE_MODELS[0];

        const assistantMsgId = `agent-${Date.now()}`;
        const initialAgentMsg = {
            id: assistantMsgId,
            role: 'assistant',
            model: activeModel.name,
            provider: activeModel.provider,
            status: 'planning',
            content: `Analyzing requirement with **${activeModel.name}**...`,
            plan: [
                { step: 1, text: `Analyze architecture for ${state.projectType.toUpperCase()} requirement`, status: 'done' },
                { step: 2, text: 'Formulate schema & component file tree', status: 'in-progress' },
                { step: 3, text: 'Compile production bundle & spin up sandbox preview', status: 'pending' }
            ],
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        };

        set((s) => ({
            messages: [...s.messages, userMsg, initialAgentMsg],
            isBuilding: true,
            buildLogs: [...s.buildLogs, `[${activeModel.name}] Generating execution plan for prompt: "${promptText}"`]
        }));

        // Simulate Plan Execution Step 1 -> Step 2
        await new Promise((r) => setTimeout(r, 1200));

        set((s) => ({
            messages: s.messages.map((m) =>
                m.id === assistantMsgId
                    ? {
                          ...m,
                          status: 'building',
                          content: `Generated execution plan via **${activeModel.name}**. Creating components and updating project files...`,
                          plan: [
                              { step: 1, text: `Analyze architecture for ${s.projectType.toUpperCase()} requirement`, status: 'done' },
                              { step: 2, text: 'Formulate schema & component file tree', status: 'done' },
                              { step: 3, text: 'Compile production bundle & spin up sandbox preview', status: 'in-progress' }
                          ]
                      }
                    : m
            ),
            buildLogs: [
                ...s.buildLogs,
                `[${activeModel.name}] Creating files: src/App.jsx, src/components/Header.jsx, server.js`,
                `[Sandbox] Hot Module Replacement (HMR) triggered`
            ]
        }));

        // Simulate File Tree Generation & HMR Update
        await new Promise((r) => setTimeout(r, 1500));

        const updatedCode = `import React, { useState } from 'react';
import { Sparkles, CheckCircle2, Shield, Activity, ArrowUpRight, Zap, Code, Users } from 'lucide-react';

export default function App() {
  const [activeTab, setActiveTab] = useState('analytics');

  return (
    <div className="min-h-screen bg-slate-950 text-white p-6 font-sans">
      <div className="max-w-6xl mx-auto space-y-6">
        {/* Top Generated Navigation */}
        <header className="flex justify-between items-center bg-slate-900/60 border border-slate-800 p-4 rounded-2xl backdrop-blur-md">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center font-bold text-white shadow-lg shadow-indigo-500/20">
              <Sparkles className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="text-sm font-extrabold tracking-tight text-white">${promptText.slice(0, 45)}...</h1>
              <p className="text-[10px] text-emerald-400 font-mono flex items-center gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-ping" /> Engine: ${activeModel.name}
              </p>
            </div>
          </div>
          <button className="bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold px-4 py-2 rounded-xl transition-all shadow-lg shadow-indigo-500/20">
            Deploy Live
          </button>
        </header>

        {/* Dynamic Metric Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
          <MetricCard title="Active Sessions" value="2,481" change="+18.4%" icon={Users} color="indigo" />
          <MetricCard title="API Throughput" value="99.98%" change="Stable" icon={Shield} color="emerald" />
          <MetricCard title="AI Agent Speed" value="1.2s avg" change="Fast" icon={Zap} color="violet" />
        </div>

        {/* Prompt Showcase Output Panel */}
        <div className="p-6 bg-slate-900/40 border border-slate-800 rounded-2xl space-y-3">
          <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" /> Real-Time App View Updated
          </h3>
          <p className="text-xs text-slate-400 leading-relaxed">
            Prompt request: <span className="text-white font-semibold">"{promptText}"</span> processed successfully by <span className="text-indigo-400 font-semibold">${activeModel.name}</span>.
          </p>
        </div>
      </div>
    </div>
  );
}

function MetricCard({ title, value, change, icon: Icon, color }) {
  return (
    <div className="p-5 bg-slate-900/60 border border-slate-800/80 rounded-2xl space-y-2">
      <div className="flex justify-between items-center text-xs">
        <span className="text-[10px] font-semibold uppercase text-slate-400 tracking-wider">{title}</span>
        <Icon className={\`w-4 h-4 text-\${color}-400\`} />
      </div>
      <h3 className="text-2xl font-black text-white">{value}</h3>
      <span className="text-[10px] font-semibold text-emerald-400 flex items-center gap-0.5">
        <ArrowUpRight className="w-3 h-3" /> {change}
      </span>
    </div>
  );
}`;

        set((s) => ({
            fileTree: {
                ...s.fileTree,
                'src/App.jsx': updatedCode
            },
            messages: s.messages.map((m) =>
                m.id === assistantMsgId
                    ? {
                          ...m,
                          status: 'ready',
                          content: `Successfully built and rendered application for prompt using **${activeModel.name}**. Live sandbox preview refreshed.`,
                          plan: [
                              { step: 1, text: `Analyze architecture for ${s.projectType.toUpperCase()} requirement`, status: 'done' },
                              { step: 2, text: 'Formulate schema & component file tree', status: 'done' },
                              { step: 3, text: 'Compile production bundle & spin up sandbox preview', status: 'done' }
                          ]
                      }
                    : m
            ),
            isBuilding: false,
            isSaved: false,
            buildLogs: [
                ...s.buildLogs,
                `[${activeModel.name}] Build completed successfully in 2.7s`,
                `[Sandbox] Bundle size: 142.8 KB | HTTP 200 OK`
            ]
        }));
    },

    // Trigger One-Click Deploy Process
    deployProject: async () => {
        const state = get();
        const slug = state.projectTitle.toLowerCase().replace(/[^a-z0-9]/g, '-');
        const generatedUrl = `https://${slug}.deepitlabs.app`;

        set({ isDeploying: true, deployLogs: ['[Build] Bundling production assets via Vite...'] });

        await new Promise((r) => setTimeout(r, 1000));
        set((s) => ({ deployLogs: [...s.deployLogs, '[DNS] Allocating wildcard subdomain SSL certificate...'] }));

        await new Promise((r) => setTimeout(r, 1200));
        set((s) => ({
            isDeploying: false,
            deployUrl: generatedUrl,
            deployLogs: [...s.deployLogs, `[Deploy] Successfully deployed to ${generatedUrl}`]
        }));
    }
}));
